USE GSSWEB
GO

SELECT TOP(5) WITH TIES 
	Book.BOOK_ID AS BookId, 
	Book.BOOK_NAME AS BookName, 
	COUNT(Book.BOOK_ID) AS Qty
FROM BOOK_DATA AS Book 
INNER JOIN BOOK_LEND_RECORD AS Lend
	ON Book.BOOK_ID = Lend.BOOK_ID
GROUP BY Book.BOOK_ID, Book.BOOK_NAME
ORDER BY Qty DESC;